title: Khalilur Rahman # your name (or website title) here
logo: "images/IMG_20190420_104422_265.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Naturally curious and passionate Android Developer. Loves traveling, Playing guitar, Hiking, Sports, Films.
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
